name: Python Daily Aggregation

on:
  schedule:
    # Runs at 00:20 UTC daily
    - cron: '20 0 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  python-daily-aggregation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install duckdb python-dotenv

      - name: Compute Yesterday's Date
        id: date
        run: |
          YESTERDAY_YEAR=$(date -d "yesterday" +'%Y')
          YESTERDAY_MONTH=$(date -d "yesterday" +'%m')
          YESTERDAY_DAY=$(date -d "yesterday" +'%d')
          echo "YESTERDAY_YEAR=${YESTERDAY_YEAR}" >> $GITHUB_ENV
          echo "YESTERDAY_MONTH=${YESTERDAY_MONTH}" >> $GITHUB_ENV
          echo "YESTERDAY_DAY=${YESTERDAY_DAY}" >> $GITHUB_ENV
          echo "Aggregating data for: ${YESTERDAY_YEAR}-${YESTERDAY_MONTH}-${YESTERDAY_DAY}"

      - name: Run daily aggregation script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ENDPOINT_URL: "data.source.coop"
          YESTERDAY_YEAR: ${{ env.YESTERDAY_YEAR }}
          YESTERDAY_MONTH: ${{ env.YESTERDAY_MONTH }}
          YESTERDAY_DAY: ${{ env.YESTERDAY_DAY }}
        run: |
          # Make the script executable
          chmod +x scripts/daily_aggregation.py
          
          # Run the script
          python scripts/daily_aggregation.py
          
          echo "Python daily aggregation completed."
